"""persist training questions and abandonment state

Revision ID: edd7b909160e
Revises: b7d5683b9277
Create Date: 2026-09-29 21:57:54.854159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd7b909160e'
down_revision = 'b7d5683b9277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    duplicate_answer = op.get_bind().execute(sa.text(
        """
        SELECT session_id, question_id
        FROM answers
        WHERE question_id IS NOT NULL
        GROUP BY session_id, question_id
        HAVING COUNT(*) > 1
        LIMIT 1
        """
    )).first()
    if duplicate_answer:
        raise RuntimeError(
            "Cannot add uq_answer_session_question: duplicate session/question "
            "answers exist. Review and resolve those records before retrying."
        )

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_answer_session_question', ['session_id', 'question_id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('second_audio_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_questions_session_id'), ['session_id'], unique=False)
        batch_op.create_unique_constraint('uq_question_session_position', ['session_id', 'position'])
        batch_op.create_foreign_key('fk_questions_second_audio', 'audios', ['second_audio_id'], ['id'])
        batch_op.create_foreign_key('fk_questions_training_session', 'training_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_abandoned', sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_abandoned')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_questions_training_session', type_='foreignkey')
        batch_op.drop_constraint('fk_questions_second_audio', type_='foreignkey')
        batch_op.drop_constraint('uq_question_session_position', type_='unique')
        batch_op.drop_index(batch_op.f('ix_questions_session_id'))
        batch_op.drop_column('second_audio_id')
        batch_op.drop_column('position')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_answer_session_question', type_='unique')

    # ### end Alembic commands ###
